### ISSUE TITLE
Can projection be done by DataAnnotations?

### ISSUE THREAD

**Issue by Clooney24** [francnuec/Neo4jClient.DataAnnotations#1]
In your following sample 

```
var results = graphClient.WithAnnotations().Cypher
.Match(path => path.Pattern<ActorNode, MovieNode>("actor", "acted_in", "movie"))
.Return((actor, movie) => new {
    Actor = actor.As<ActorNode>(),
    Movies = movie.CollectAs<MovieNode>()
})
.Results
```
the return value will be an object containing the properties Actor and Movies. But Actor already has the property Movies. Is it possible to use projection so only the Actor-class is needed as a result with the Actor.Movies-Property is filled with the movies collection? 

In our actual c# code we do this using an extra `.WITH`-Command, something like this:
```
.With("Actor { .*, Movies:COLLECT(movie)}")
```
It would be perfect if this could also be done by DataAnnotation so no pure Cypher will be needed for this projection. All necessary information should exist in the given annotations.

**Comment by francnuec** [comment]
Hi @Clooney24 . So sorry for replying this late, I've been overwhelmed with work.

I think projections would be nice to have. I can definitely work on it, the issue is when (my day work nowadays is pretty demanding). But if you can figure it out, I would be happy to include it from your PR.

However, a few other things to note. A larger chunk of the serialization is handled by the underlying Neo4jClient library. If you check [this issue here](https://github.com/Readify/Neo4jClient/issues/213), you would see that Neo4jClient hasn't handled Map Projections yet, so this can make it harder for our implementations. For work arounds, your way of extra WITH is fine, but you can also take a look at some of their [suggestions here](https://github.com/Readify/Neo4jClient/issues/214) which you can easily translate to annotations.
